#!/usr/bin/env php
<?php

/**
 *
 *  
 *  @author Lutfi Aulia Sidik 
 **/

use Kurumi\Consoles\Command;
use Kurumi\Container\Container;
use samejack\PHP\ArgvParser;


// Registari composer autoload... 
require_once __DIR__ . '/vendor/autoload.php';

// Kurumi Bootstrap 
require_once __DIR__ . '/bootstrap/app.php';

// Call command...
$argvParser = new ArgvParser();

Container::getInstance()
    ->make(Command::class)->handleCommand($argvParser->parseConfigs());

